### ISSUE TITLE
Add some description to the main page with how to submit conferences

### ISSUE THREAD

**Issue by witchy-mutant** [callForPapers/callForPapers.github.io#10]

**Comment by cmatskas** [comment]
One step further, add a form to make it easy to submit CfPs

**Comment by cmatskas** [comment]
I'll add the simple instructions in the ReadMe file

**Comment by kkokosa** [comment]
I believe we should add simple sentence on main page pointing to the github repository?

**Comment by cmatskas** [comment]
Do you want a link to the GitHub repo on the ReadMe file? Should this not be a separate issue?

**Comment by kkokosa** [comment]
Not on the ReadMe but on the main page (cfp.help) :)

**Comment by ptrstpp950** [comment]
I will try to do this today during the flight

**Comment by ptrstpp950** [comment]
I submitted new page with all the information. I reused @cmatskas information from readme file

**Comment by witchy-mutant** [comment]
Are we closing this then?

**Comment by ptrstpp950** [comment]
Yes
