### ISSUE TITLE
Column widths - tags are too wide, date is too narrow

### ISSUE THREAD

**Issue by witchy-mutant** [callForPapers/callForPapers.github.io#11]

**Comment by kkokosa** [comment]
I believe "tags" should be on the second row of the description (with span on all columns) and with smaller font size.

**Comment by cmatskas** [comment]
I think we could redesign the table to provide more information in a better format. Something like a card with all the details in two columns. Not as searchable as the current version but better for presenting information quickly. I reckon that this site could eventually grow to be big but for now basic is good. Anything outside the standard table format and the table sorting etc wont work. 

@mihcall  Out of curiosity does the bootstrap table support paging and filtering as well? If not, should we not be looking at a better alternative? (jquery datatables springs to mind)

**Comment by kkokosa** [comment]
@cmatskas Bootstrap table was choosen because of its 'RWDness' and yes, they do support paging. Yet some redesign of the table will be necessary for sure:)

**Comment by Biegal** [comment]
I've set some static width on date columns for now

**Comment by witchy-mutant** [comment]
Good for now, huh? Closing?
