### ISSUE TITLE
Add <noscript> tag

### ISSUE THREAD

**Issue by taurit** [callForPapers/callForPapers.github.io#25]
Currently the front page appears as an empty table with headers for users blocking javascript (eg. with _NoScript_ browser addon).

Adding a message using HTML's `<noscript>` tag could make it obvious for such users that the page is not broken (or has no data), but that they have to enable JavaScript.

Here's example of such simple message displayed only to users without JS support.

![noscript-message](https://cloud.githubusercontent.com/assets/7702278/11376465/1dee0340-92e1-11e5-85a1-9a5c0c4008e3.png)

**Comment by ptrstpp950** [comment]
if you would like to change the message or format just let me know
