### ISSUE TITLE
Add tech stack tags to each entry

### ISSUE THREAD

**Issue by cmatskas** [callForPapers/callForPapers.github.io#3]
Each row should contain info/tags on the technology discussed at each conference. This way, we can quickly sort (column filter) on the ones relevant e.g. .NET, AI, Docker, DevOps etc

**Comment by ptrstpp950** [comment]
@cmatskas don't we have this already? we have tags+quick filter. Do you think about something else?

**Comment by cmatskas** [comment]
We have indeed. This can now be closed. It was raised before @mihcall added support for tags.
