### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by kkokosa** [callForPapers/callForPapers.github.io#41]
As cfp.help is getting more popular (isn't it?), I believe it would be nice to add some analytics - will allow to track and report traffic.

**Comment by cmatskas** [comment]
Does it not need to be under someone's account? It's easy to add, I've done it many times, as long as we can get an account and tracking code. Suggestions?

**Comment by kkokosa** [comment]
Yes, the account - it is required. I have one, I've generated tracking code. 

@cmatskas, @ptrstpp950 @mihcall - please provide yours Google accounts so I can add access to it.

```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-61243294-5', 'auto');
  ga('send', 'pageview');

</script>
```

**Comment by cmatskas** [comment]
```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-72020144-1', 'auto');
  ga('send', 'pageview');

</script>
```

Thanks

**Comment by witchy-mutant** [comment]
m.sliwon@gmail.com as on github

**Comment by ptrstpp950** [comment]
Mine you have :)

wt., 5.01.2016 o 18:30 użytkownik Michał Śliwoń notifications@github.com
napisał:

**Comment by cmatskas** [comment]
Christos.matskas@gmail.com

**Comment by ptrstpp950** [comment]
@mihcall why don't you have firstname.surname@gmail.com? others have exactly this pattern :)

**Comment by kkokosa** [comment]
@cmatskas, @ptrstpp950 @mihcall - all added :)

**Comment by cmatskas** [comment]
Closing :)

**Comment by ptrstpp950** [comment]
@cmatskas but @kkokosa didn't make a commit yet

**Comment by cmatskas** [comment]
Sorry, trigger happy :(

**Comment by witchy-mutant** [comment]
I have firstname.surname@gmail.com as well but most of my stuff is connected to m.sliwon@gmail.com and I have all my google analytics sites there for example :)

**Comment by witchy-mutant** [comment]
And yes, tracking isn't added yet as there are no results.

**Comment by kkokosa** [comment]
I will try to add it today - as easy as it is, did not have time even for that..

**Comment by witchy-mutant** [comment]
No problem, I can do this :)

**Comment by witchy-mutant** [comment]
Are we using jekyll for anything at the moment? @ptrstpp950 ?

**Comment by ptrstpp950** [comment]
For merging cfp json files into one big file

**Comment by witchy-mutant** [comment]
But not for generating index.html, right? I was a bit confused where to put GA script because there's default layout template :)

**Comment by witchy-mutant** [comment]
Ok, script kicked in, we can close now :)

**Comment by cmatskas** [comment]
Closing, just cause I like doing this :)

**Comment by witchy-mutant** [comment]
I specifically didn't do it myself so that you can do it @cmatskas :)

**Comment by cmatskas** [comment]
Lol, @mihcall  you know me sooo well!
